version: '3.8'

services:
  pdfa-converter-api:
    build: .
    container_name: pdfa-converter-engine
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - NODE_ENV=production
